Nivel3 laverinto
Fanny-Pack-Studios/endless-game-kit-2d pull request #32
Opened 2024-09-11 21:00 UTC by jphm22

Se creo el laberinto para el nivel  y se le agrego la decoración con la configuración del ordering

2024-09-12 17:33 UTC, JuanFdS requested changes
¡Me gusta!
Y creo que la imagen que pasaste por discord estaría bueno que sea parte de la descripción del pull request:
![image](https://github.com/user-attachments/assets/97e54807-0ed3-4855-a5f4-85d920c30ce4)

Tengo algunas cosas para discutir, las escribo sobre la imagen directamente. Contestame **1** y **2** y según en lo que nos pongamos de acuerdo decidimos si hay que hacer algún cambio más o lo dejamos así. **3** es un comentario que creo que mejor revisarlo más adelante.

![image psd(55)](https://github.com/user-attachments/assets/b3836755-4746-496b-9040-f680248596de)

## 1
¿Y si ponemos a los personajes que dan pistas **antes** de las bifurcaciones?, así alguien que sabe inglés podría realizar el laberinto solo siguiendo las pistas sin tener que adivinar prácticamente nada.

## 2
¿Qué opinas acerca de agregar también algunos "caminos sin salida" pero que tengan recompensas? Por ejemplo, que al hablar con el NPC marcado en el mapa con el **2** te de un objeto que te pueda servir para curarte durante el próximo combate.

## 3
No está marcado en la imagen, pero creo que por el tamaño del laberinto y la cámara por defecto, se puede ver mucho hacia adelante. Podríamos solucionar esto haciendo el nivel más grande. Sin embargo, dejemos esto para luego de haber implementado #36 , así no estamos modificando el nivel a ciegas.

2024-09-13 12:59 UTC, JuanFdS reviewed
No estoy seguro si estaba para review, pero dejé un comentario

2024-09-13 12:59 UTC, JuanFdS commented on godot/scenes/jp_escena_prueba/Laberinto.tscn
> +scale = Vector2(0.939861, 1.00872)
¿Por qué esta escalado el jugador?

2024-09-13 17:49 UTC, jphm22 commented on godot/scenes/jp_escena_prueba/Laberinto.tscn
> +scale = Vector2(0.939861, 1.00872)
Lo coloque de nuevo a x=1 e y=1. Tengo problemas con el ordering y el z index. Creo que ese seria el paso para concluir esta actividad

2024-09-13 18:11 UTC, merged